const {chromium}=require('playwright');const assert=require('assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.AURA_CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const p=await b.newPage({viewport:{width:1440,height:900},acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000/dist/index.html');await p.waitForFunction(()=>aura.workbench);await p.click('#skipArrival');
const routes=await p.evaluate(async()=>{const {walkRoute}=await import('/src/house/navigation.js'),h=aura.house;const views=[[0,24],[-16,25],[-16,4.7],[16,4.5],[16,24],[-14,-14],[4,6.7],[0,-15],[15,-15]];let count=0;for(const a of views)for(const z of views){const route=walkRoute(h.architecture,{x:a[0],z:a[1]},{x:z[0],z:z[1]});if(!route)throw Error('No route '+a+' -> '+z);for(let i=1;i<route.length;i++){const u=route[i-1],v=route[i],n=Math.ceil(Math.hypot(v.x-u.x,v.z-u.z)/.1);for(let j=0;j<=n;j++)if(!h.architecture.canWalk(u.x+(v.x-u.x)*j/n,u.z+(v.z-u.z)*j/n))throw Error('Collision '+JSON.stringify([a,z,u,v]));}count++;}return count;});assert.equal(routes,81);assert.equal(await p.evaluate(()=>aura.house.architecture.interactive.filter(o=>o.userData.action?.type==='note').length),88);console.log('81 collision-free room routes and 88 actual piano keys: PASS');
await p.click('#houseWorkbenchButton');await p.selectOption('#wbVoice','organ');await p.keyboard.down('a');await p.waitForTimeout(180);assert.equal(await p.evaluate(()=>aura.workbench.performance.held.size),1);await p.keyboard.up('a');assert.equal(await p.evaluate(()=>aura.workbench.performance.held.size),0);
await p.click('#wbCapture');await p.waitForTimeout(2300);await p.keyboard.down('a');await p.waitForTimeout(250);await p.keyboard.up('a');await p.evaluate(()=>aura.workbench.performance.finish());assert.ok(await p.evaluate(()=>aura.store.project.tracks[0].clips[0].notes.some(n=>n.pitch===60&&n.start<2&&n.duration<1)));console.log('Held note and real MIDI count-in capture: PASS');
const dsp=await p.evaluate(async()=>{const {makeTrack,makeClip}=await import('/src/project.js'),{makeEffect}=await import('/src/effects.js'),{measureBuffer}=await import('/src/analysis.js');const t=makeTrack('keys');t.reverb=0;const c=makeClip('note',0,1);c.notes=[{id:'n',pitch:60,start:0,duration:.4,velocity:.7}];t.clips=[c];const project={bpm:120,bars:1,master:.7,swing:0,tracks:[t],assets:{}};const dry=measureBuffer(await aura.engine.render(project)).rms,result=[];for(const type of ['eq','compressor','delay','saturation','chorus','tremolo','filter','width']){const fx=makeEffect(type);if(type==='eq')fx.params.gain=12;if(type==='filter')fx.params.frequency=3000;if(type==='width')fx.params.width=0;t.inserts=[fx];const metrics=measureBuffer(await aura.engine.render(project));fx.enabled=false;const bypass=measureBuffer(await aura.engine.render(project));result.push({type,rms:metrics.rms,bypass:bypass.rms,dry});}return result;});assert.ok(dsp.every(x=>Number.isFinite(x.rms)&&Math.abs(x.bypass-x.dry)<1e-6));assert.ok(dsp.find(x=>x.type==='saturation').rms>dsp[0].dry*1.5);assert.ok(dsp.find(x=>x.type==='filter').rms<dsp[0].dry*.4);console.log('ALL EIGHT INSERTS / exact bypass + audible gain and filter behavior',dsp);
// A real two-channel WAV reference, loaded through the file input.
await p.evaluate(async()=>{const {encodeWav}=await import('/src/audio.js');await aura.engine.init();const ctx=aura.engine.ctx,buf=ctx.createBuffer(2,48000*4,48000);for(let ch=0;ch<2;ch++)for(let i=0;i<buf.length;i++)buf.getChannelData(ch)[i]=Math.sin(2*Math.PI*220*i/48000)*.1;window.refBytes=Array.from(new Uint8Array(encodeWav(buf)));});const ref=Buffer.from(await p.evaluate(()=>refBytes));await p.click('[data-wbtab="listen"]');await p.setInputFiles('#wbReference',{name:'Measured-reference.wav',mimeType:'audio/wav',buffer:ref});await p.waitForFunction(()=>aura.workbench.reference);await p.click('#wbMatch');await p.waitForFunction(()=>!aura.workbench.busy);assert.ok(await p.evaluate(()=>aura.workbench.reference.gain>0));await p.click('#wbListenB');assert.ok(await p.evaluate(()=>aura.workbench.refSource));await p.waitForTimeout(180);assert.ok(await p.evaluate(()=>aura.engine.projectOutput.gain.value<.01));await p.click('#wbListenA');assert.ok(await p.evaluate(()=>!aura.workbench.refSource));await p.click('#wbPlay');console.log('Decoded reference, full render RMS match and actual A/B gates: PASS');
await p.click('[data-wbtab="samples"]');await p.setInputFiles('#wbImportAudio',{name:'Reference-as-sample.wav',mimeType:'audio/wav',buffer:ref});await p.waitForFunction(()=>Object.keys(aura.store.project.assets).length===1);const assetId=await p.evaluate(()=>Object.keys(aura.store.project.assets)[0]);await p.click('[data-favorite="'+assetId+'"]');assert.ok(await p.evaluate(()=>Object.values(aura.store.project.assets)[0].favorite));await p.evaluate(()=>{const el=document.querySelector('#wbClipGain');el.value=.5;el.dispatchEvent(new Event('change'));});await p.click('#wbReverseAudio');assert.ok(await p.evaluate(()=>aura.store.project.tracks.at(-1).clips[0].reverse));console.log('Decoded sample waveform, favorites, clip gain and reverse: PASS');
// Keep two audible tracks to make a bounded end-to-end ZIP.
await p.evaluate(()=>aura.store.commit('Stem test',project=>project.tracks.forEach((t,i)=>t.mute=i>1)));await p.click('[data-wbtab="export"]');const event=p.waitForEvent('download',{timeout:60000});await p.click('#wbExportStems');const download=await event;await download.saveAs(__dirname+'/v3-stems.zip');console.log('ACTUAL ALIGNED STEM ZIP: PASS');assert.deepEqual(errors,[]);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
