const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'/workspace/scratch/05bbde1e20dc/browser-runtime/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],badRequests=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/favicon.ico'))badRequests.push({url:r.url(),status:r.status()});});
 await page.addInitScript(()=>{localStorage.setItem('aura-intro','off');localStorage.setItem('aura-house-reduced','true');localStorage.setItem('aura-house-quality','performance');});
 await page.goto('http://localhost:3000/dist/index.html');await page.waitForFunction(()=>window.aura?.house?.renderer&&window.aura?.game);await page.evaluate(()=>aura.house.renderer.setAnimationLoop(null));
 await page.evaluate(()=>aura.house.modelsReady);const models=await page.evaluate(()=>({loaded:aura.house.models.loaded,errors:aura.house.models.errors}));assert.equal(models.loaded.length,5);assert.deepEqual(models.errors,[]);console.log('All five supplied models loaded');
 const routes=await page.evaluate(async()=>{const {walkRoute}=await import('/src/house/navigation.js');const a=aura.house.architecture,ids=['gallery','idea','instrument','rhythm','record','arrange','living','master','terrace'],targets={};for(const id of ids){aura.house.goRoom(id,true);targets[id]={x:aura.house.camera.position.x,z:aura.house.camera.position.z};}let count=0,fail=[];for(const i of ids)for(const j of ids){const route=walkRoute(a,targets[i],targets[j]);if(route)count++;else fail.push(i+'→'+j);}return {count,fail};});assert.equal(routes.count,81,JSON.stringify(routes));
 for(const room of (process.env.AURA_VERIFY_SHORT?[]:['living','idea','record','gallery','terrace'])){await page.evaluate(room=>{const h=aura.house;h.goRoom(room,true);h.camera.updateMatrixWorld();h.renderer.render(h.scene,h.camera);},room);await page.screenshot({path:'docs/update-0.4/room-'+room+'.jpg',timeout:60000});console.log('Captured',room);}
 await page.evaluate(()=>{aura.house.returnHouse();aura.coach.open();});const before=await page.evaluate(()=>JSON.stringify(aura.store.project));await page.click('[data-lesson="chords"]');assert.equal(await page.evaluate(()=>JSON.stringify(aura.store.project)),before);
 await page.click('#coachPractice');await page.click('#coachPractice');const practice=await page.evaluate(()=>aura.store.project.tracks.filter(t=>t.name==='Practice · Build your first chord').length);assert.equal(practice,1);assert.equal(await page.evaluate(()=>document.activeElement.id),'coachPractice');await page.click('#coachCheck');await page.click('[data-answer="0"]');assert.ok((await page.locator('#coachQuizFeedback').innerText()).startsWith('That’s right.'));
 await page.fill('#coachQuestion','How do I make a melody? <img src=x onerror=window.pwned=true>');await page.click('#coachAsk');assert.equal(await page.evaluate(()=>window.pwned),undefined);assert.ok((await page.locator('.coachMessages').innerText()).includes('Guided answer'));
 await page.screenshot({path:'docs/update-0.4/music-coach.jpg'});
 await page.click('#coachListen');await page.waitForFunction(()=>aura.engine.playing);const audioBefore=await page.evaluate(()=>{window.updateAudioGraph=aura.engine.g;return {origin:aura.engine.origin,graph:!!aura.engine.g};});await page.evaluate(()=>aura.game.open());assert.equal(await page.evaluate(()=>aura.engine.playing),true);
 await page.click('#gameStart');await page.keyboard.down('ArrowLeft');await page.waitForFunction(()=>aura.game.state.paddle<.4);await page.keyboard.up('ArrowLeft');assert.equal(await page.evaluate(()=>aura.house.keys.size),0);await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>aura.game.running),false);assert.equal(await page.evaluate(()=>aura.engine.playing),true);const audioAfter=await page.evaluate(()=>({origin:aura.engine.origin,graph:!!aura.engine.g}));assert.deepEqual(audioAfter,audioBefore);assert.equal(await page.evaluate(()=>aura.engine.g===window.updateAudioGraph),true);
 const rms=await page.evaluate(()=>{const m=aura.engine.metrics();return {peak:m.peak,rms:m.rms};});assert.ok(rms.rms>.001);const footer=await page.locator('#gameMusic').boundingBox(),dialog=await page.locator('#chillGame').boundingBox();assert.ok(footer.y+footer.height<=dialog.y+dialog.height);await page.screenshot({path:'docs/update-0.4/sundown-rally.jpg'});console.log('Game keyboard input preserves transport',rms);
 await page.click('#gameClose');assert.equal(await page.evaluate(()=>aura.game.running),false);await page.evaluate(()=>aura.engine.stop());await page.evaluate(()=>aura.coach.open('chords'));assert.equal(await page.evaluate(()=>aura.coach.progress.chords),true);await page.click('[data-coach-close]');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>aura.coach.open());await page.screenshot({path:'docs/update-0.4/coach-mobile.jpg',fullPage:true});const mobile=await page.evaluate(()=>({dialog:document.querySelector('#musicCoach').scrollWidth,width:document.querySelector('#musicCoach').clientWidth}));assert.ok(mobile.dialog<=mobile.width+2,JSON.stringify(mobile));await page.evaluate(()=>aura.game.open());await page.screenshot({path:'docs/update-0.4/game-mobile.jpg'});assert.equal(await page.evaluate(()=>document.querySelector('#chillGame').scrollWidth<=document.querySelector('#chillGame').clientWidth+2),true);
 await page.evaluate(()=>document.querySelector('#chillGame').close());await page.keyboard.press('Control+s');await page.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Saved locally'));await page.reload();await page.waitForFunction(()=>!!window.aura?.coach);await page.evaluate(()=>aura.house.renderer.setAnimationLoop(null));assert.equal(await page.evaluate(()=>aura.coach.progress.chords),true);assert.equal(await page.evaluate(()=>aura.store.project.tracks.filter(t=>t.name==='Practice · Build your first chord').length),1);
 assert.deepEqual(errors,[]);assert.deepEqual(badRequests,[]);fs.writeFileSync('docs/update-0.4/verification.json',JSON.stringify({models,routes,practiceTracks:practice,mobile,audioBefore,audioAfter,rms,errors,badRequests},null,2));await browser.close();console.log('UPDATE WORKFLOW PASSED');
})().catch(e=>{console.error(e);process.exit(1)});
